version: '2.4'

services:

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    restart: "unless-stopped"
    command: ["server"]
    network_mode: "host"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    environment:
      - K3S_TOKEN=${K3S_TOKEN:?err}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./k3s-server:/var/lib/rancher/k3s
      # This is just so that we get the kubeconfig file out
      - ./output:/output
    mem_limit: 1024m
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
