version: '3'
services:

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    restart: "unless-stopped"
    command: ["server", "--node-external-ip", "192.168.1.199"]
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_TOKEN=${K3S_TOKEN:?err}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ./k3s-server:/var/lib/rancher/k3s
      # This is just so that we get the kubeconfig file out
      - ./output:/output
    ports:
      - 6443:6443
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
