---
- hosts: node
  vars_files:
    - vars/default.yml
    - vars/user.yml
  tasks:

    - name: Stop and Remove services defined in docker-compose.yml
      command: docker-compose -f /home/{{ username }}/k3s-node/docker-compose.yml rm -fs
