---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

    - name: Update the APT packages index
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install all required packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Add APT signing key from official Docker repo
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker official repository for Ubuntu Focal
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update the APT packages index
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Actually install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Adding existing user "{{ user }}" to docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Install packages via PIP
      pip:
        name:
          - docker
          - docker-compose
