version: '3'
services:

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    restart: "unless-stopped"
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_URL=https://192.168.1.199:6443
      - K3S_TOKEN=${K3S_TOKEN:?err}
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
