version: '3'

services:

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    restart: "unless-stopped"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    environment:
      - K3S_URL=https://k8s-controller:6443
      - K3S_TOKEN=983d7454-20ae-11eb-b0db-ff72ee78a062
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
